// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGvPwBqKw6w7Iw2_l72g24a6mCP-DlPL8',
    appId: '1:239218464581:web:ee49ce56f51b1aa177d02c',
    messagingSenderId: '239218464581',
    projectId: 'kahel-cba6e',
    authDomain: 'kahel-cba6e.firebaseapp.com',
    databaseURL: 'https://kahel-cba6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kahel-cba6e.appspot.com',
    measurementId: 'G-4BKZRHJHKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFBJTCTiK7EWS-DuSl_LpDi9kF99oGe88',
    appId: '1:239218464581:android:f81aa0a0c64af39d77d02c',
    messagingSenderId: '239218464581',
    projectId: 'kahel-cba6e',
    databaseURL: 'https://kahel-cba6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kahel-cba6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqIIABLzKANJv_mpvLNAbFmS9TGLGuYXM',
    appId: '1:239218464581:ios:af7d97e4fe69680877d02c',
    messagingSenderId: '239218464581',
    projectId: 'kahel-cba6e',
    databaseURL: 'https://kahel-cba6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kahel-cba6e.appspot.com',
    iosBundleId: 'com.example.kahel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqIIABLzKANJv_mpvLNAbFmS9TGLGuYXM',
    appId: '1:239218464581:ios:af7d97e4fe69680877d02c',
    messagingSenderId: '239218464581',
    projectId: 'kahel-cba6e',
    databaseURL: 'https://kahel-cba6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kahel-cba6e.appspot.com',
    iosBundleId: 'com.example.kahel',
  );
}
